version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: military_mysql
    restart: always
    environment:
      MYSQL_DATABASE: military_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - military_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: military_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # PENTING: DB_HOST pake nama service yaitu 'db'
      DB_HOST: db
      DB_USER: root
      DB_PASS: rootpassword
      DB_NAME: military_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - military_network

volumes:
  db_data:

networks:
  military_network:
    driver: bridge